<a href="https://colab.research.google.com/github/vineelabaisa9119/2216119_AIML_BootCamp/blob/main/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
df=pd.read_csv('/content/SUV_Purchase.csv')
df.head(20)

User ID  Gender  Age  EstimatedSalary  Purchased
0   15624510    Male   19            19000          0
1   15810944    Male   35            20000          0
2   15668575  Female   26            43000          0
3   15603246  Female   27            57000          0
4   15804002    Male   19            76000          0
5   15728773    Male   27            58000          0
6   15598044  Female   27            84000          0
7   15694829  Female   32           150000          1
8   15600575    Male   25            33000          0
9   15727311  Female   35            65000          0
10  15570769  Female   26            80000          0
11  15606274  Female   26            52000          0
12  15746139    Male   20            86000          0
13  15704987    Male   32            18000          0
14  15628972    Male   18            82000          0
15  15697686    Male   29            80000          0
16  15733883    Male   47            25000          1
17  15617482    Male   45            26000          1
18  15704583    Male   46            28000          1
19  15621083  Female   48            29000          1

In [21]:
df = df.drop('User ID',axis=1)
df = df.drop('Gender',axis=1)

In [22]:
# Importing StandardScaler from scikit-learn
from sklearn.preprocessing import StandardScaler
sst = StandardScaler()
data_scaled=df.iloc[:,:-1].values
data_scaled=sst.fit_transform(data_scaled)
data_scaled=pd.DataFrame(data_scaled)

In [23]:
data_scaled.head()

0         1
0 -1.781797 -1.490046
1 -0.253587 -1.460681
2 -1.113206 -0.785290
3 -1.017692 -0.374182
4 -1.781797  0.183751

In [24]:
data_scaled.columns=['Age','EstimatedSalary']
data_scaled.head()

Age  EstimatedSalary
0 -1.781797        -1.490046
1 -0.253587        -1.460681
2 -1.113206        -0.785290
3 -1.017692        -0.374182
4 -1.781797         0.183751

In [25]:
data_scaled['Purchased'] = df.Purchased

In [26]:
data_scaled = data_scaled[data_scaled['Purchased'].notna()]

In [27]:
data_scaled

Age  EstimatedSalary  Purchased
0   -1.781797        -1.490046          0
1   -0.253587        -1.460681          0
2   -1.113206        -0.785290          0
3   -1.017692        -0.374182          0
4   -1.781797         0.183751          0
..        ...              ...        ...
395  0.797057        -0.844019          1
396  1.274623        -1.372587          1
397  1.179110        -1.460681          1
398 -0.158074        -1.078938          0
399  1.083596        -0.990844          1

[400 rows x 3 columns]

In [28]:
#X=df.iloc[:,-3:-1].values #loading the independent column values into X
#Y=df.iloc[:,-1:].values #loading the dependent values into Y

import numpy as np
x=np.array(data_scaled[['EstimatedSalary','Age']])
y=np.array(data_scaled[['Purchased']])

In [30]:
print(x)

[[-1.49004624 -1.78179743]
 [-1.46068138 -0.25358736]
 [-0.78528968 -1.11320552]
 [-0.37418169 -1.01769239]
 [ 0.18375059 -1.78179743]
 [-0.34481683 -1.01769239]
 [ 0.41866944 -1.01769239]
 [ 2.35674998 -0.54012675]
 [-1.07893824 -1.20871865]
 [-0.13926283 -0.25358736]
 [ 0.30121002 -1.11320552]
 [-0.52100597 -1.11320552]
 [ 0.47739916 -1.6862843 ]
 [-1.51941109 -0.54012675]
 [ 0.35993973 -1.87731056]
 [ 0.30121002 -0.82666613]
 [-1.3138571   0.89257019]
 [-1.28449224  0.70154394]
 [-1.22576253  0.79705706]
 [-1.19639767  0.98808332]
 [-1.40195167  0.70154394]
 [-0.60910054  0.89257019]
 [-0.84401939  0.98808332]
 [-1.40195167  0.70154394]
 [-1.37258681  0.79705706]
 [-1.46068138  0.89257019]
 [-1.22576253  1.08359645]
 [-1.16703281  0.89257019]
 [-0.78528968 -0.82666613]
 [-1.51941109 -0.63563988]
 [ 0.12502088 -0.63563988]
 [ 1.97500684 -1.01769239]
 [-1.5781408  -1.59077117]
 [-0.75592482 -0.92217926]
 [ 0.59485858 -1.01769239]
 [-1.25512738 -0.25358736]
 [-1.22576253 -0.44461362]
 

In [32]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [34]:
print(x)

[[-1.49004624 -1.78179743]
 [-1.46068138 -0.25358736]
 [-0.78528968 -1.11320552]
 [-0.37418169 -1.01769239]
 [ 0.18375059 -1.78179743]
 [-0.34481683 -1.01769239]
 [ 0.41866944 -1.01769239]
 [ 2.35674998 -0.54012675]
 [-1.07893824 -1.20871865]
 [-0.13926283 -0.25358736]
 [ 0.30121002 -1.11320552]
 [-0.52100597 -1.11320552]
 [ 0.47739916 -1.6862843 ]
 [-1.51941109 -0.54012675]
 [ 0.35993973 -1.87731056]
 [ 0.30121002 -0.82666613]
 [-1.3138571   0.89257019]
 [-1.28449224  0.70154394]
 [-1.22576253  0.79705706]
 [-1.19639767  0.98808332]
 [-1.40195167  0.70154394]
 [-0.60910054  0.89257019]
 [-0.84401939  0.98808332]
 [-1.40195167  0.70154394]
 [-1.37258681  0.79705706]
 [-1.46068138  0.89257019]
 [-1.22576253  1.08359645]
 [-1.16703281  0.89257019]
 [-0.78528968 -0.82666613]
 [-1.51941109 -0.63563988]
 [ 0.12502088 -0.63563988]
 [ 1.97500684 -1.01769239]
 [-1.5781408  -1.59077117]
 [-0.75592482 -0.92217926]
 [ 0.59485858 -1.01769239]
 [-1.25512738 -0.25358736]
 [-1.22576253 -0.44461362]
 

In [36]:
print(x,y)

[[-1.49004624 -1.78179743]
 [-1.46068138 -0.25358736]
 [-0.78528968 -1.11320552]
 [-0.37418169 -1.01769239]
 [ 0.18375059 -1.78179743]
 [-0.34481683 -1.01769239]
 [ 0.41866944 -1.01769239]
 [ 2.35674998 -0.54012675]
 [-1.07893824 -1.20871865]
 [-0.13926283 -0.25358736]
 [ 0.30121002 -1.11320552]
 [-0.52100597 -1.11320552]
 [ 0.47739916 -1.6862843 ]
 [-1.51941109 -0.54012675]
 [ 0.35993973 -1.87731056]
 [ 0.30121002 -0.82666613]
 [-1.3138571   0.89257019]
 [-1.28449224  0.70154394]
 [-1.22576253  0.79705706]
 [-1.19639767  0.98808332]
 [-1.40195167  0.70154394]
 [-0.60910054  0.89257019]
 [-0.84401939  0.98808332]
 [-1.40195167  0.70154394]
 [-1.37258681  0.79705706]
 [-1.46068138  0.89257019]
 [-1.22576253  1.08359645]
 [-1.16703281  0.89257019]
 [-0.78528968 -0.82666613]
 [-1.51941109 -0.63563988]
 [ 0.12502088 -0.63563988]
 [ 1.97500684 -1.01769239]
 [-1.5781408  -1.59077117]
 [-0.75592482 -0.92217926]
 [ 0.59485858 -1.01769239]
 [-1.25512738 -0.25358736]
 [-1.22576253 -0.44461362]
 

In [37]:
#spliting the data  into training and testing set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [38]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test=sc.transform(x_train)

In [39]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [40]:
print("Predicted value for training data:",model.score(x_train,y_train))


Predicted value for training data: 0.884375


In [42]:
model.score(x,y)

0.8975

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

NameError: ignored

In [ ]:
y_train=y_train.flatten()

In [ ]:
import matplotlib.pyplot as plt
from matplotlib. colors import ListedColormap
x_set, y_set = sst.inverse_transform(x_train),y_train
x1,x2 = np.meshgrid(np. arange(start = x_set[:, 0].min( )-10,stop= x_set[:, 0].max() + 10, step = 0.25) ,
np.arange(start = x_set[:, 1].min( )- 1000, stop = x_set[:, 1].max ( ) + 1000, step = 0.25))
plt. contourf(x1,x2,model.predict(sst.transform(np.array([x1.ravel(), x2.ravel()]). T) ).reshape (x1. shape ),
alpha = 0.75, map = ListedColormap(('red','green' )) )
plt. xlim(x1.min( ), x1.max( ))
plt.ylim(x2.min( ), x2. max( ))
for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j,0],x_set[y_set ==j,1],c = ListedColormap(('red','green'))(i),label=j)
plt. title('Logistic Regression (Training set)')
plt.xlabel('Age')
plt. ylabel('Estimated Salary')
plt. legend()
plt.show()

In [ ]:
y_test=y_test.flatten()

In [ ]:
from matplotlib. colors import ListedColormap
x_set, y_set = sst.inverse_transform(x_test),y_test
x1,x2 = np.meshgrid(np. arange(start = x_set[:, 0].min( )-10,stop= x_set[:, 0].max() + 10, step = 0.25) ,
np.arange(start = x_set[:, 1].min( )- 1000, stop = x_set[:, 1].max ( ) + 1000, step = 0.25))
plt. contourf(x1,x2,model.predict(sst.transform(np.array([x1.ravel(), x2.ravel()]). T) ).reshape (x1. shape ),
alpha = 0.75, map = ListedColormap(('red','green' )) )
plt. xlim(x1.min( ), x1.max( ))
plt.ylim(x2.min( ), x2. max( ))
for i, j in enumerate(np.unique(y_set)):
  plt.scatter(x_set[y_set == j,0],x_set[y_set ==j,1],c = ListedColormap(('red','green'))(i),label=j)
plt. title('Logistic Regression (Testing set)')
plt.xlabel('Age')
plt. ylabel('Estimated Salary')
plt. legend()
plt.show()